version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: financiacel_app
    volumes:
      - ./backend:/var/www
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: financiacel_web
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: financiacel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: financiacel
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    image: node:20-alpine
    container_name: financiacel_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  pgdata: